# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dd08a833feb69f5941493479d7bc703f673bef844c1e977d61eda699fb0575eb138bd1b7ee5d9260e841e02d5d96329d5b298215bf86e1a50cf67f8cfac4a7e

test:
  secret_key_base: 31650372c7646ad62abc27cb6cc602658ca65d2be3dc91f229657db654f13eb44b9e2522f4aeef08ff848d9f4d74e977f4cd7f6043a8b784cf3c7b48392bb632

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
